# Generated by Django 4.1.4 on 2023-06-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('store', '0002_remove_product_image'),
    # ]
        dependencies = [
                ('store', '0001_initial'),
            ]
        operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
