# Generated by Django 4.1.4 on 2023-06-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_image'),
        ('store', '0003_product_image'),
    ]

    operations = [
    ]
