# Generated by Django 4.1.4 on 2023-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
