# Generated by Django 4.1.4 on 2023-06-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
